version: '2'

services:
  nginx:
    image: nginx:latest
    container_name: nginx01
    ports:
      - "80:80"
    expose:
      - "80"
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: django01
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn ouvidoria.wsgi -b 0.0.0.0:8000"
    volumes:
      - .:/code
    expose:
      - "8000"