# Generated by Django 2.1 on 2018-08-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='ano',
            field=models.IntegerField(),
        ),
    ]
