# Generated by Django 2.1 on 2018-08-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0003_jogador'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='posicao',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='nota',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='telefone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
