# Generated by Django 2.1 on 2018-08-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0004_auto_20180824_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='numero_camisa',
            field=models.IntegerField(null=True),
        ),
    ]
