# Generated by Django 2.1 on 2018-08-27 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0005_jogador_numero_camisa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dh_partida', models.DateTimeField()),
                ('local', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('status', models.CharField(max_length=1)),
                ('qtd_jogadores', models.IntegerField()),
                ('time1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time1', to='clubes.Time')),
                ('time2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time2', to='clubes.Time')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
            },
        ),
    ]
