# Generated by Django 2.1 on 2018-08-27 14:28

import clubes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0006_partida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('ativo', models.CharField(default='S', max_length=1)),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
            },
        ),
        migrations.CreateModel(
            name='PartidaConfirmacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dh_confirmacao', models.DateTimeField(auto_now_add=True)),
                ('confirmado', models.CharField(max_length=1)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Partida')),
            ],
            options={
                'verbose_name': 'PartidaConfirmacao',
                'verbose_name_plural': 'PartidasConfirmacoes',
            },
        ),
        migrations.CreateModel(
            name='PartidaGol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols', models.IntegerField()),
                ('tipo_gol', models.CharField(choices=[('AFAVOR', 'A'), ('CONTRA', 'C')], default=clubes.models.TipoGol('A'), max_length=1)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Partida')),
            ],
            options={
                'verbose_name': 'PartidaGol',
                'verbose_name_plural': 'PartidaGols',
            },
        ),
        migrations.CreateModel(
            name='PartidaIndicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dh_votacao', models.DateTimeField(auto_now_add=True)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Indicador')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Partida')),
            ],
            options={
                'verbose_name': 'PartidaIndicador',
                'verbose_name_plural': 'PartidaIndicadores',
            },
        ),
        migrations.CreateModel(
            name='PartidaNota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dh_votacao', models.DateTimeField(auto_now_add=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Partida')),
            ],
            options={
                'verbose_name': 'PartidaNota',
                'verbose_name_plural': 'PartidaNota',
            },
        ),
    ]
