# Generated by Django 2.1 on 2018-09-13 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0008_clube_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='JogadorClube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensalista', models.BooleanField(default=True)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubes.Clube')),
            ],
            options={
                'verbose_name': 'Jogador Clube',
                'verbose_name_plural': 'Jogadores Clubes',
            },
        ),
        migrations.AddField(
            model_name='jogador',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='nome',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jogadorclube',
            name='jogador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Jogador'),
        ),
    ]
