# Generated by Django 2.1 on 2018-09-24 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubes', '0009_auto_20180913_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='nota',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='numero_camisa',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='posicao',
        ),
        migrations.RemoveField(
            model_name='jogadorclube',
            name='jogador',
        ),
        migrations.AddField(
            model_name='jogador',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='jogadorclube',
            name='nota',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='jogadorclube',
            name='numero_camisa',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jogadorclube',
            name='posicao',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='jogadorclube',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='jogador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jogadorclube',
            name='clube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Clube'),
        ),
    ]
