# Generated by Django 2.1 on 2018-09-25 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubes', '0012_auto_20180925_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogadorclube',
            name='clube',
        ),
        migrations.AddField(
            model_name='jogadorclube',
            name='clube',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubes.Clube'),
        ),
        migrations.RemoveField(
            model_name='jogadorclube',
            name='usuario',
        ),
        migrations.AddField(
            model_name='jogadorclube',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
