# Generated by Django 2.1 on 2018-09-26 00:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubes', '0013_auto_20180925_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='data_nascimento',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='telefone',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='jogadorclube',
            unique_together={('usuario', 'clube')},
        ),
    ]
