# Generated by Django 2.1 on 2018-09-26 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0014_auto_20180926_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clube',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='data_inscricao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jogadorclube',
            name='clube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Clube'),
        ),
        migrations.AlterField(
            model_name='jogadorclube',
            name='data_membro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jogadorclube',
            name='nota',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='jogadorclube',
            name='numero_camisa',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='jogadorclube',
            name='posicao',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='jogadorclube',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
