# Generated by Django 2.1 on 2018-09-26 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0015_auto_20180926_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='clube',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubes.Clube'),
        ),
    ]
