# Generated by Django 2.1.2 on 2018-12-13 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0018_auto_20181009_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidaconfirmacao',
            name='jogador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogador', to='clubes.Jogador'),
        ),
    ]
